theme: jekyll-theme-slate

title: "A New Panopticon"
description: "[In progress] Data, power, and the modern world"

collections:
  'front-matter':
    output: true
  'chapter-01':
    output: true
  'chapter-02':
    output: true
  'chapter-03':
    output: true
