theme: jekyll-theme-slate

title: "A New Panopticon"
description: "[In progress] Data, power, and the modern world"
baseurl: 'https://morungos.com/panopticon'

collections:
  'front-matter':
    output: true