theme: jekyll-theme-slate

title: "A New Panopticon"
description: "How power, data, and artificial intelligence are transforming our society"

collections:
  'front-matter':
    output: false
  'chapter-01':
    output: false
  'chapter-02':
    output: false
  'chapter-03':
    output: false
  'chapter-04':
    output: false
  'chapter-05':
    output: false
